# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcExampleService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18GrpcExampleService.proto\"=\n\x12\x43lientsInfoRequest\x12\'\n\x0b\x63lientsinfo\x18\x01 \x03(\x0b\x32\x12.ClientInfoRequest\"\x0c\n\nResponseOk\"\x0e\n\x0c\x45mptyRequest\"?\n\x11\x43lientInfoRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\"L\n\x12\x43lientInfoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05login\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\";\n\x13\x43lientsInfoResponse\x12$\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x13.ClientInfoResponse\"(\n\x17GetClientByLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\"Q\n\rResponseError\x12/\n\x13response_error_code\x18\x01 \x01(\x0e\x32\x12.ResponseErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"j\n\x0e\x61\x64\x64\x43lientReply\x12\"\n\x0bresponse_ok\x18\x01 \x01(\x0b\x32\x0b.ResponseOkH\x00\x12(\n\x0eresponse_error\x18\x02 \x01(\x0b\x32\x0e.ResponseErrorH\x00\x42\n\n\x08Response\"y\n\x0fGetClientsReply\x12\x30\n\x10response_clients\x18\x01 \x01(\x0b\x32\x14.ClientsInfoResponseH\x00\x12(\n\x0eresponse_error\x18\x02 \x01(\x0b\x32\x0e.ResponseErrorH\x00\x42\n\n\x08Response*N\n\x11ResponseErrorCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x18\n\x14RESPONSE_BAD_REQUEST\x10\x01\x12\x12\n\x0eRESPONSE_ERROR\x10\x02\x32\xbc\x01\n\x12GrpcExampleService\x12\x33\n\tAddClient\x12\x13.ClientsInfoRequest\x1a\x0f.addClientReply\"\x00\x12/\n\nGetClients\x12\r.EmptyRequest\x1a\x10.GetClientsReply\"\x00\x12@\n\x10GetClientByLogin\x12\x18.GetClientByLoginRequest\x1a\x10.GetClientsReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GrpcExampleService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSEERRORCODE']._serialized_start=681
  _globals['_RESPONSEERRORCODE']._serialized_end=759
  _globals['_CLIENTSINFOREQUEST']._serialized_start=28
  _globals['_CLIENTSINFOREQUEST']._serialized_end=89
  _globals['_RESPONSEOK']._serialized_start=91
  _globals['_RESPONSEOK']._serialized_end=103
  _globals['_EMPTYREQUEST']._serialized_start=105
  _globals['_EMPTYREQUEST']._serialized_end=119
  _globals['_CLIENTINFOREQUEST']._serialized_start=121
  _globals['_CLIENTINFOREQUEST']._serialized_end=184
  _globals['_CLIENTINFORESPONSE']._serialized_start=186
  _globals['_CLIENTINFORESPONSE']._serialized_end=262
  _globals['_CLIENTSINFORESPONSE']._serialized_start=264
  _globals['_CLIENTSINFORESPONSE']._serialized_end=323
  _globals['_GETCLIENTBYLOGINREQUEST']._serialized_start=325
  _globals['_GETCLIENTBYLOGINREQUEST']._serialized_end=365
  _globals['_RESPONSEERROR']._serialized_start=367
  _globals['_RESPONSEERROR']._serialized_end=448
  _globals['_ADDCLIENTREPLY']._serialized_start=450
  _globals['_ADDCLIENTREPLY']._serialized_end=556
  _globals['_GETCLIENTSREPLY']._serialized_start=558
  _globals['_GETCLIENTSREPLY']._serialized_end=679
  _globals['_GRPCEXAMPLESERVICE']._serialized_start=762
  _globals['_GRPCEXAMPLESERVICE']._serialized_end=950
# @@protoc_insertion_point(module_scope)
